server:
  port: 8084



spring:
  datasource:
    url: jdbc:mysql://localhost:3307/product
    username: root
    password: password

#kafka:
#  bootstrap-servers: localhost:9092
#  consumer:
#    enabled: true
#    consumers:
#      - topic: product-created
#        groupId: product-service
#        concurrency: 2
#      - topic: product-updated
#        groupId: product-service
#        concurrency: 2


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

