apiVersion: v1
kind: Secret
metadata:
  name: common-core-secret
  namespace: sme-hub
type: Opaque
data:
  # Replace the base64-encoded strings below with your values
  DATABASE_URL: dXNlcjpwYXNzd29yZEAxMjcuMC4wLjE= # Example: user:password@127.0.0.1
  API_KEY: QWxhZGRpbjpvcGVuIHNlc2FtZQ== # Example: Aladdin:open sesame
